# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/bookaroo.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18src/proto/bookaroo.proto\"l\n\x07Request\x12\x16\n\x0e\x63ollectionName\x18\x01 \x01(\t\x12\x1d\n\toperation\x18\x02 \x01(\x0e\x32\n.Operation\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\x12\r\n\x05query\x18\x05 \x01(\t\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t*;\n\tOperation\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06SELECT\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x32\x32\n\x10RequestProcessor\x12\x1e\n\x07process\x12\x08.Request\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.bookaroo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPERATION']._serialized_start=181
  _globals['_OPERATION']._serialized_end=240
  _globals['_REQUEST']._serialized_start=28
  _globals['_REQUEST']._serialized_end=136
  _globals['_RESPONSE']._serialized_start=138
  _globals['_RESPONSE']._serialized_end=179
  _globals['_REQUESTPROCESSOR']._serialized_start=242
  _globals['_REQUESTPROCESSOR']._serialized_end=292
# @@protoc_insertion_point(module_scope)
