FROM python:3.9

WORKDIR /usr/src/app
#COPY pyproject.toml .
#COPY pdm.lock .
#RUN pdm install

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . /usr/src/app

CMD ["python", "./src/main.py"]
#RUN python ./src/main.py