FROM python:3.9

RUN pip install pdm
RUN pip install google-api-python-client
#RUN pip install uvicorn


WORKDIR /usr/src/app
#COPY pyproject.toml .
#COPY pdm.lock .
#RUN pdm install
#RUN pdm remove pymongo
#RUN pdm install
#RUN pdm add pymongo
#RUN pdm install
#RUN mkdir __pypackages__ && pdm sync --prod --no-editable

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . /usr/src/app
#CMD ["pdm", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["uvicorn", "src.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
#CMD ["pdm", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000" ]
