FROM python:3.11

RUN pip install pdm

WORKDIR /usr/src/app
COPY pyproject.toml .
COPY pdm.lock .
RUN pdm install

COPY ./src /usr/src/app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
